---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ./metadata
  - ./requirements
  - ../../components/pcihole64
  - ../../components/interfacemodel-rtl8139

nameSuffix: ".2k3"
