---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  # https://docs.oracle.com/en/operating-systems/oracle-linux/limits/
  requirements:
    cpu:
      guest: 2
    memory:
      guest: 4Gi
