---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: metadata
  annotations:
    tags: "hidden,kubevirt,oraclelinux"
    iconClass: "icon-oracle"
    openshift.io/display-name: "Oracle Linux"
