---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  # https://learn.microsoft.com/en-us/windows-server/get-started/hardware-requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
